import {
  seedgraphCore,
  pruneCore,
  graftCore,
  rerootCore,
  swapCore,
  retipCore,
  entwineOpCore,
  canopyCore,
  trellisCore,
  wanderCore,
  selectCore,
  pathCore,
  matchCore,
  sproutCore,
  utteranceCore,
  graftBranch,
  graftBud,
  graftLeaf,
  graftVine,
  pruneBranch,
  pruneBud,
  pruneLeaf,
  pruneVine,
  assay,
  inspectCore,
} from "../ops/index.js";
import { actionDirective } from "../runtime/action.js";
import { ctxDirective } from "../runtime/ctx.js";
import { guardDirective } from "../runtime/guard.js";

export const coreRegistry = {
  seedgraph: seedgraphCore,
  prune: pruneCore,
  graft: graftCore,
  reroot: rerootCore,
  swap: swapCore,
  retip: retipCore,
  entwine: entwineOpCore,
  canopy: canopyCore,
  trellis: trellisCore,
  wander: wanderCore,
  select: selectCore,
  path: pathCore,
  match: matchCore,
  sprout: sproutCore,
  realize: sproutCore,
  utterance: utteranceCore,

  graftbranch: graftBranch,
  graftbud: graftBud,
  graftleaf: graftLeaf,
  graftvine: graftVine,
  "graft.branch": graftBranch,
  "graft.bud": graftBud,
  "graft.leaf": graftLeaf,
  "graft.vine": graftVine,

  prunebranch: pruneBranch,
  prunebud: pruneBud,
  pruneleaf: pruneLeaf,
  prunevine: pruneVine,
  "prune.branch": pruneBranch,
  "prune.bud": pruneBud,
  "prune.leaf": pruneLeaf,
  "prune.vine": pruneVine,

  assay,
  inspect: inspectCore,
  action: actionDirective,
  ctx: ctxDirective,
  guard: guardDirective,
};
