export const ACTION_VOCABULARY = [
  "ADD_ITEM",
  "CONSUME_ITEM",
  "REMOVE_ITEM",
  "ANALYZE_INVENTORY",
  "ANALYZE_ITEM_BY_ID",
  "RESOLVE_ITEM_STATUS",
  "UPDATE_THRESHOLD",
  "UPDATE_EXPIRATION_COUNTS",
  "UPDATE_RESTOCK_POLICY",
  "UPDATE_ITEM_CATEGORY",
  "UPDATE_ITEM_NAME",
  "UPDATE_ITEM_SHELF_LIFE",
  "RESOLVE_RECOMMENDATION",
  "RECOMMEND_PANTRY_ACTIONS",
  "RANK_PANTRY_PRIORITIES",
  "GENERATE_SHOPPING_LIST",
]

export const EVENT_VOCABULARY = [
  "ITEM_ADDED",
  "ITEM_CONSUMED",
  "ITEM_REMOVED",
  "INVENTORY_ANALYZED",
  "ITEM_ANALYZED",
  "RESTOCK_POLICY_UPDATED",
  "ITEM_CATEGORY_UPDATED",
  "ITEM_NAME_UPDATED",
  "ITEM_SHELF_LIFE_UPDATED",
  "RECOMMENDATION_RESOLVED",
  "PANTRY_RECOMMENDATIONS_GENERATED",
  "PANTRY_PRIORITIES_RANKED",
  "SHOPPING_LIST_GENERATED",
]

const ACTION_SET = new Set(ACTION_VOCABULARY)
const EVENT_SET = new Set(EVENT_VOCABULARY)

export function isUpperSnakeCase(value) {
  return typeof value === "string" && /^[A-Z][A-Z0-9_]*$/.test(value)
}

export function isKnownAction(value) {
  return ACTION_SET.has(value)
}

export function isKnownEvent(value) {
  return EVENT_SET.has(value)
}
